use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let demo_dir = manifest_dir.join("..").join("demo-vault");
    let out_file = manifest_dir.join("src").join("generated_demo_vault.rs");

    // Re-run build.rs whenever any file inside demo-vault changes.
    println!("cargo:rerun-if-changed={}", demo_dir.display());

    let mut entries: Vec<String> = Vec::new();
    collect_files(&demo_dir, "", &mut entries);
    entries.sort();

    // Build include_str! calls. Paths are relative to src-tauri/src/ where the
    // generated file lives, so we prefix with ../../demo-vault/.
    let mut code = String::from(
        "// AUTO-GENERATED by build.rs from demo-vault/ directory.\n\
         // Do not edit manually — just add/remove files in demo-vault/.\n\n\
         pub fn demo_vault_files() -> Vec<(&'static str, &'static str)> {\n\
             vec![\n",
    );
    for rel in &entries {
        let abs = format!("../../demo-vault/{}", rel.replace('\\', "/"));
        code.push_str(&format!(
            "        (\"{rel}\", include_str!(\"{abs}\")),\n",
            rel = rel.replace('\\', "/"),
            abs = abs,
        ));
    }
    code.push_str("    ]\n}\n");

    // Only overwrite if content changed to avoid invalidating incremental builds.
    let current = fs::read_to_string(&out_file).unwrap_or_default();
    if current != code {
        fs::write(&out_file, code).expect("Failed to write generated_demo_vault.rs");
    }

    tauri_build::build()
}

fn collect_files(base: &Path, prefix: &str, out: &mut Vec<String>) {
    let dir = if prefix.is_empty() {
        base.to_path_buf()
    } else {
        base.join(prefix)
    };
    let iter = match fs::read_dir(&dir) {
        Ok(iter) => iter,
        Err(_) => return,
    };
    for entry in iter.flatten() {
        let name = entry.file_name();
        let name_str = name.to_string_lossy();
        if name_str == ".thinkingkity" {
            continue;
        }
        let path = entry.path();
        let rel = if prefix.is_empty() {
            name_str.to_string()
        } else {
            format!("{}/{}", prefix, name_str)
        };
        if path.is_dir() {
            collect_files(base, &rel, out);
        } else {
            out.push(rel);
        }
    }
}
