import type { CompletionContext, CompletionResult } from "@codemirror/autocomplete";

interface KeywordGroup {
  label: string;
  type: string;
  detail?: string;
  boost?: number;
}

function makeCompletions(keywords: KeywordGroup[]) {
  return keywords.map((k) => ({
    label: k.label,
    type: k.type,
    detail: k.detail,
    boost: k.boost ?? 0,
  }));
}

const pythonKeywords: KeywordGroup[] = [
  { label: "False", type: "constant", detail: "boolean", boost: 1 },
  { label: "True", type: "constant", detail: "boolean", boost: 1 },
  { label: "None", type: "constant", detail: "null", boost: 1 },
  { label: "and", type: "keyword", detail: "operator" },
  { label: "as", type: "keyword", detail: "alias" },
  { label: "assert", type: "keyword" },
  { label: "async", type: "keyword" },
  { label: "await", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "class", type: "keyword", detail: "definition", boost: 1 },
  { label: "continue", type: "keyword" },
  { label: "def", type: "keyword", detail: "definition", boost: 1 },
  { label: "del", type: "keyword" },
  { label: "elif", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "except", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "from", type: "keyword" },
  { label: "global", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "import", type: "keyword", boost: 1 },
  { label: "in", type: "keyword" },
  { label: "is", type: "keyword" },
  { label: "lambda", type: "keyword" },
  { label: "nonlocal", type: "keyword" },
  { label: "not", type: "keyword" },
  { label: "or", type: "keyword" },
  { label: "pass", type: "keyword" },
  { label: "raise", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "with", type: "keyword" },
  { label: "yield", type: "keyword" },
  { label: "print", type: "function", detail: "builtin", boost: 2 },
  { label: "len", type: "function", detail: "builtin", boost: 2 },
  { label: "range", type: "function", detail: "builtin", boost: 2 },
  { label: "input", type: "function", detail: "builtin", boost: 2 },
  { label: "int", type: "class", detail: "builtin", boost: 2 },
  { label: "float", type: "class", detail: "builtin", boost: 2 },
  { label: "str", type: "class", detail: "builtin", boost: 2 },
  { label: "list", type: "class", detail: "builtin", boost: 2 },
  { label: "dict", type: "class", detail: "builtin", boost: 2 },
  { label: "tuple", type: "class", detail: "builtin", boost: 2 },
  { label: "set", type: "class", detail: "builtin", boost: 2 },
  { label: "bool", type: "class", detail: "builtin", boost: 2 },
  { label: "type", type: "function", detail: "builtin", boost: 2 },
  { label: "isinstance", type: "function", detail: "builtin", boost: 2 },
  { label: "enumerate", type: "function", detail: "builtin", boost: 2 },
  { label: "zip", type: "function", detail: "builtin", boost: 2 },
  { label: "map", type: "function", detail: "builtin", boost: 2 },
  { label: "filter", type: "function", detail: "builtin", boost: 2 },
  { label: "sorted", type: "function", detail: "builtin", boost: 2 },
  { label: "reversed", type: "function", detail: "builtin", boost: 2 },
  { label: "open", type: "function", detail: "builtin", boost: 2 },
  { label: "super", type: "function", detail: "builtin", boost: 2 },
  { label: "getattr", type: "function", detail: "builtin", boost: 2 },
  { label: "setattr", type: "function", detail: "builtin", boost: 2 },
  { label: "hasattr", type: "function", detail: "builtin", boost: 2 },
  { label: "abs", type: "function", detail: "builtin", boost: 2 },
  { label: "min", type: "function", detail: "builtin", boost: 2 },
  { label: "max", type: "function", detail: "builtin", boost: 2 },
  { label: "sum", type: "function", detail: "builtin", boost: 2 },
  { label: "any", type: "function", detail: "builtin", boost: 2 },
  { label: "all", type: "function", detail: "builtin", boost: 2 },
  { label: "hex", type: "function", detail: "builtin", boost: 2 },
  { label: "oct", type: "function", detail: "builtin", boost: 2 },
  { label: "chr", type: "function", detail: "builtin", boost: 2 },
  { label: "ord", type: "function", detail: "builtin", boost: 2 },
  { label: "id", type: "function", detail: "builtin", boost: 2 },
  { label: "repr", type: "function", detail: "builtin", boost: 2 },
  { label: "format", type: "function", detail: "builtin", boost: 2 },
  { label: "property", type: "function", detail: "builtin", boost: 2 },
  { label: "staticmethod", type: "function", detail: "builtin", boost: 2 },
  { label: "classmethod", type: "function", detail: "builtin", boost: 2 },
  { label: "__init__", type: "function", detail: "dunder", boost: 2 },
  { label: "__str__", type: "function", detail: "dunder", boost: 2 },
  { label: "__repr__", type: "function", detail: "dunder", boost: 2 },
  { label: "__len__", type: "function", detail: "dunder", boost: 2 },
  { label: "__getitem__", type: "function", detail: "dunder", boost: 2 },
  { label: "__setitem__", type: "function", detail: "dunder", boost: 2 },
  { label: "__iter__", type: "function", detail: "dunder", boost: 2 },
  { label: "__next__", type: "function", detail: "dunder", boost: 2 },
  { label: "__eq__", type: "function", detail: "dunder", boost: 2 },
  { label: "__hash__", type: "function", detail: "dunder", boost: 2 },
  { label: "__add__", type: "function", detail: "dunder", boost: 2 },
  { label: "__name__", type: "property", detail: "module", boost: 2 },
  { label: "__main__", type: "property", detail: "module", boost: 2 },
  { label: "self", type: "variable", boost: 3 },
  { label: "cls", type: "variable", boost: 3 },
];

const javaKeywords: KeywordGroup[] = [
  { label: "abstract", type: "keyword" },
  { label: "assert", type: "keyword" },
  { label: "boolean", type: "type", boost: 1 },
  { label: "break", type: "keyword" },
  { label: "byte", type: "type" },
  { label: "case", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "char", type: "type" },
  { label: "class", type: "keyword", boost: 1 },
  { label: "const", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "double", type: "type" },
  { label: "else", type: "keyword" },
  { label: "enum", type: "keyword", boost: 1 },
  { label: "extends", type: "keyword" },
  { label: "final", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "float", type: "type" },
  { label: "for", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "implements", type: "keyword" },
  { label: "import", type: "keyword", boost: 1 },
  { label: "instanceof", type: "keyword" },
  { label: "int", type: "type", boost: 1 },
  { label: "interface", type: "keyword", boost: 1 },
  { label: "long", type: "type" },
  { label: "native", type: "keyword" },
  { label: "new", type: "keyword", boost: 1 },
  { label: "package", type: "keyword", boost: 1 },
  { label: "private", type: "keyword", boost: 1 },
  { label: "protected", type: "keyword", boost: 1 },
  { label: "public", type: "keyword", boost: 1 },
  { label: "return", type: "keyword" },
  { label: "short", type: "type" },
  { label: "static", type: "keyword", boost: 1 },
  { label: "strictfp", type: "keyword" },
  { label: "super", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "synchronized", type: "keyword" },
  { label: "this", type: "keyword", boost: 1 },
  { label: "throw", type: "keyword" },
  { label: "throws", type: "keyword" },
  { label: "transient", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "void", type: "type", boost: 1 },
  { label: "volatile", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "System", type: "class", detail: "java.lang", boost: 2 },
  { label: "String", type: "class", detail: "java.lang", boost: 2 },
  { label: "Integer", type: "class", detail: "java.lang", boost: 2 },
  { label: "Long", type: "class", detail: "java.lang", boost: 2 },
  { label: "Double", type: "class", detail: "java.lang", boost: 2 },
  { label: "Float", type: "class", detail: "java.lang", boost: 2 },
  { label: "Boolean", type: "class", detail: "java.lang", boost: 2 },
  { label: "Object", type: "class", detail: "java.lang", boost: 2 },
  { label: "Math", type: "class", detail: "java.lang", boost: 2 },
  { label: "Exception", type: "class", detail: "java.lang", boost: 2 },
  { label: "RuntimeException", type: "class", detail: "java.lang", boost: 2 },
  { label: "IOException", type: "class", detail: "java.io", boost: 2 },
  { label: "ArrayList", type: "class", detail: "java.util", boost: 2 },
  { label: "HashMap", type: "class", detail: "java.util", boost: 2 },
  { label: "HashSet", type: "class", detail: "java.util", boost: 2 },
  { label: "LinkedList", type: "class", detail: "java.util", boost: 2 },
  { label: "List", type: "interface", detail: "java.util", boost: 2 },
  { label: "Map", type: "interface", detail: "java.util", boost: 2 },
  { label: "Set", type: "interface", detail: "java.util", boost: 2 },
  { label: "Optional", type: "class", detail: "java.util", boost: 2 },
  { label: "Arrays", type: "class", detail: "java.util", boost: 2 },
  { label: "Collections", type: "class", detail: "java.util", boost: 2 },
  { label: "Thread", type: "class", detail: "java.lang", boost: 2 },
  { label: "Runnable", type: "interface", detail: "java.lang", boost: 2 },
  { label: "Override", type: "annotation", boost: 2 },
  { label: "Deprecated", type: "annotation", boost: 2 },
  { label: "SuppressWarnings", type: "annotation", boost: 2 },
  { label: "FunctionalInterface", type: "annotation", boost: 2 },
  { label: "true", type: "constant", boost: 1 },
  { label: "false", type: "constant", boost: 1 },
  { label: "null", type: "constant", boost: 1 },
];

const rustKeywords: KeywordGroup[] = [
  { label: "as", type: "keyword" },
  { label: "async", type: "keyword" },
  { label: "await", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "crate", type: "keyword" },
  { label: "dyn", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "enum", type: "keyword", boost: 1 },
  { label: "extern", type: "keyword" },
  { label: "fn", type: "keyword", detail: "function", boost: 1 },
  { label: "for", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "impl", type: "keyword", boost: 1 },
  { label: "in", type: "keyword" },
  { label: "let", type: "keyword", boost: 1 },
  { label: "loop", type: "keyword" },
  { label: "match", type: "keyword", boost: 1 },
  { label: "mod", type: "keyword" },
  { label: "move", type: "keyword" },
  { label: "mut", type: "keyword", boost: 1 },
  { label: "pub", type: "keyword", boost: 1 },
  { label: "ref", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "Self", type: "type" },
  { label: "self", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "struct", type: "keyword", boost: 1 },
  { label: "super", type: "keyword" },
  { label: "trait", type: "keyword", boost: 1 },
  { label: "type", type: "keyword" },
  { label: "unsafe", type: "keyword" },
  { label: "use", type: "keyword", boost: 1 },
  { label: "where", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "true", type: "constant", boost: 1 },
  { label: "false", type: "constant", boost: 1 },
  { label: "i8", type: "type", boost: 2 },
  { label: "i16", type: "type", boost: 2 },
  { label: "i32", type: "type", boost: 2 },
  { label: "i64", type: "type", boost: 2 },
  { label: "i128", type: "type", boost: 2 },
  { label: "isize", type: "type", boost: 2 },
  { label: "u8", type: "type", boost: 2 },
  { label: "u16", type: "type", boost: 2 },
  { label: "u32", type: "type", boost: 2 },
  { label: "u64", type: "type", boost: 2 },
  { label: "u128", type: "type", boost: 2 },
  { label: "usize", type: "type", boost: 2 },
  { label: "f32", type: "type", boost: 2 },
  { label: "f64", type: "type", boost: 2 },
  { label: "bool", type: "type", boost: 2 },
  { label: "char", type: "type", boost: 2 },
  { label: "str", type: "type", boost: 2 },
  { label: "String", type: "class", detail: "std::string", boost: 2 },
  { label: "Vec", type: "class", detail: "std::vec", boost: 2 },
  { label: "HashMap", type: "class", detail: "std::collections", boost: 2 },
  { label: "HashSet", type: "class", detail: "std::collections", boost: 2 },
  { label: "Option", type: "enum", detail: "std::option", boost: 2 },
  { label: "Result", type: "enum", detail: "std::result", boost: 2 },
  { label: "Some", type: "constant", detail: "Option variant" },
  { label: "None", type: "constant", detail: "Option variant" },
  { label: "Ok", type: "constant", detail: "Result variant" },
  { label: "Err", type: "constant", detail: "Result variant" },
  { label: "Box", type: "class", detail: "std::box", boost: 2 },
  { label: "Rc", type: "class", detail: "std::rc", boost: 2 },
  { label: "Arc", type: "class", detail: "std::sync", boost: 2 },
  { label: "println!", type: "function", detail: "macro", boost: 3 },
  { label: "eprintln!", type: "function", detail: "macro", boost: 2 },
  { label: "format!", type: "function", detail: "macro", boost: 2 },
  { label: "vec!", type: "function", detail: "macro", boost: 2 },
  { label: "assert!", type: "function", detail: "macro", boost: 2 },
  { label: "assert_eq!", type: "function", detail: "macro", boost: 2 },
  { label: "assert_ne!", type: "function", detail: "macro", boost: 2 },
  { label: "panic!", type: "function", detail: "macro", boost: 2 },
  { label: "todo!", type: "function", detail: "macro", boost: 2 },
  { label: "unimplemented!", type: "function", detail: "macro", boost: 2 },
  { label: "unreachable!", type: "function", detail: "macro", boost: 2 },
  { label: "dbg!", type: "function", detail: "macro", boost: 2 },
  { label: "macro_rules!", type: "keyword", detail: "macro def" },
  { label: "derive", type: "annotation", detail: "attribute", boost: 2 },
  { label: "allow", type: "annotation", detail: "attribute" },
  { label: "warn", type: "annotation", detail: "attribute" },
  { label: "deny", type: "annotation", detail: "attribute" },
  { label: "cfg", type: "annotation", detail: "attribute" },
  { label: "test", type: "annotation", detail: "attribute" },
  { label: "bench", type: "annotation", detail: "attribute" },
];

const goKeywords: KeywordGroup[] = [
  { label: "break", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "chan", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "defer", type: "keyword", boost: 1 },
  { label: "else", type: "keyword" },
  { label: "fallthrough", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "func", type: "keyword", boost: 1 },
  { label: "go", type: "keyword" },
  { label: "goto", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "import", type: "keyword", boost: 1 },
  { label: "interface", type: "keyword", boost: 1 },
  { label: "map", type: "type" },
  { label: "package", type: "keyword", boost: 1 },
  { label: "range", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "select", type: "keyword" },
  { label: "struct", type: "keyword", boost: 1 },
  { label: "switch", type: "keyword" },
  { label: "type", type: "keyword", boost: 1 },
  { label: "var", type: "keyword", boost: 1 },
  { label: "true", type: "constant", boost: 1 },
  { label: "false", type: "constant", boost: 1 },
  { label: "nil", type: "constant", boost: 1 },
  { label: "iota", type: "constant", boost: 1 },
  { label: "bool", type: "type", boost: 2 },
  { label: "int", type: "type", boost: 2 },
  { label: "int8", type: "type", boost: 2 },
  { label: "int16", type: "type", boost: 2 },
  { label: "int32", type: "type", boost: 2 },
  { label: "int64", type: "type", boost: 2 },
  { label: "uint", type: "type", boost: 2 },
  { label: "uint8", type: "type", boost: 2 },
  { label: "uint16", type: "type", boost: 2 },
  { label: "uint32", type: "type", boost: 2 },
  { label: "uint64", type: "type", boost: 2 },
  { label: "float32", type: "type", boost: 2 },
  { label: "float64", type: "type", boost: 2 },
  { label: "complex64", type: "type", boost: 2 },
  { label: "complex128", type: "type", boost: 2 },
  { label: "byte", type: "type", detail: "alias uint8", boost: 2 },
  { label: "rune", type: "type", detail: "alias int32", boost: 2 },
  { label: "string", type: "type", boost: 2 },
  { label: "error", type: "interface", boost: 2 },
  { label: "any", type: "interface", detail: "interface{}", boost: 2 },
  { label: "len", type: "function", detail: "builtin", boost: 2 },
  { label: "cap", type: "function", detail: "builtin", boost: 2 },
  { label: "make", type: "function", detail: "builtin", boost: 2 },
  { label: "new", type: "function", detail: "builtin", boost: 2 },
  { label: "append", type: "function", detail: "builtin", boost: 2 },
  { label: "copy", type: "function", detail: "builtin", boost: 2 },
  { label: "delete", type: "function", detail: "builtin", boost: 2 },
  { label: "close", type: "function", detail: "builtin", boost: 2 },
  { label: "panic", type: "function", detail: "builtin", boost: 2 },
  { label: "recover", type: "function", detail: "builtin", boost: 2 },
  { label: "println", type: "function", detail: "builtin", boost: 2 },
  { label: "printf", type: "function", detail: "builtin", boost: 2 },
];

const jsTsKeywords: KeywordGroup[] = [
  { label: "break", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "class", type: "keyword", boost: 1 },
  { label: "const", type: "keyword", boost: 1 },
  { label: "continue", type: "keyword" },
  { label: "debugger", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "delete", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "export", type: "keyword", boost: 1 },
  { label: "extends", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "function", type: "keyword", boost: 1 },
  { label: "if", type: "keyword" },
  { label: "import", type: "keyword", boost: 1 },
  { label: "in", type: "keyword" },
  { label: "instanceof", type: "keyword" },
  { label: "let", type: "keyword", boost: 1 },
  { label: "new", type: "keyword" },
  { label: "of", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "super", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "this", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "typeof", type: "keyword" },
  { label: "var", type: "keyword" },
  { label: "void", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "with", type: "keyword" },
  { label: "yield", type: "keyword" },
  { label: "true", type: "constant", boost: 1 },
  { label: "false", type: "constant", boost: 1 },
  { label: "null", type: "constant", boost: 1 },
  { label: "undefined", type: "constant", boost: 1 },
  { label: "NaN", type: "constant" },
  { label: "Infinity", type: "constant" },
  { label: "console", type: "variable", boost: 2 },
  { label: "log", type: "function", detail: "console", boost: 2 },
  { label: "warn", type: "function", detail: "console", boost: 2 },
  { label: "error", type: "function", detail: "console", boost: 2 },
  { label: "Array", type: "class", boost: 2 },
  { label: "Object", type: "class", boost: 2 },
  { label: "String", type: "class", boost: 2 },
  { label: "Number", type: "class", boost: 2 },
  { label: "Boolean", type: "class", boost: 2 },
  { label: "Map", type: "class", boost: 2 },
  { label: "Set", type: "class", boost: 2 },
  { label: "Promise", type: "class", boost: 2 },
  { label: "Error", type: "class", boost: 2 },
  { label: "Date", type: "class", boost: 2 },
  { label: "RegExp", type: "class", boost: 2 },
  { label: "Math", type: "variable", boost: 2 },
  { label: "JSON", type: "variable", boost: 2 },
  { label: "parseInt", type: "function", boost: 2 },
  { label: "parseFloat", type: "function", boost: 2 },
  { label: "isNaN", type: "function", boost: 2 },
  { label: "isFinite", type: "function", boost: 2 },
  { label: "encodeURI", type: "function", boost: 2 },
  { label: "decodeURI", type: "function", boost: 2 },
  { label: "encodeURIComponent", type: "function", boost: 2 },
  { label: "decodeURIComponent", type: "function", boost: 2 },
  { label: "setTimeout", type: "function", boost: 2 },
  { label: "setInterval", type: "function", boost: 2 },
  { label: "clearTimeout", type: "function", boost: 2 },
  { label: "clearInterval", type: "function", boost: 2 },
  { label: "fetch", type: "function", boost: 2 },
  { label: "require", type: "function", boost: 2 },
];

const tsExtraKeywords: KeywordGroup[] = [
  { label: "type", type: "keyword", detail: "TS type alias", boost: 1 },
  { label: "interface", type: "keyword", detail: "TS", boost: 1 },
  { label: "enum", type: "keyword", detail: "TS", boost: 1 },
  { label: "implements", type: "keyword", detail: "TS" },
  { label: "declare", type: "keyword", detail: "TS" },
  { label: "abstract", type: "keyword", detail: "TS" },
  { label: "as", type: "keyword", detail: "TS" },
  { label: "satisfies", type: "keyword", detail: "TS" },
  { label: "keyof", type: "keyword", detail: "TS" },
  { label: "typeof", type: "keyword", detail: "TS" },
  { label: "infer", type: "keyword", detail: "TS" },
  { label: "readonly", type: "keyword", detail: "TS" },
  { label: "namespace", type: "keyword", detail: "TS" },
  { label: "extends", type: "keyword", detail: "TS generics", boost: 1 },
  { label: "never", type: "type", detail: "TS" },
  { label: "unknown", type: "type", detail: "TS" },
  { label: "any", type: "type", detail: "TS" },
  { label: "void", type: "type", detail: "TS" },
  { label: "Record", type: "type", detail: "TS utility", boost: 2 },
  { label: "Partial", type: "type", detail: "TS utility", boost: 2 },
  { label: "Required", type: "type", detail: "TS utility", boost: 2 },
  { label: "Readonly", type: "type", detail: "TS utility", boost: 2 },
  { label: "Pick", type: "type", detail: "TS utility", boost: 2 },
  { label: "Omit", type: "type", detail: "TS utility", boost: 2 },
  { label: "Exclude", type: "type", detail: "TS utility", boost: 2 },
  { label: "Extract", type: "type", detail: "TS utility", boost: 2 },
  { label: "ReturnType", type: "type", detail: "TS utility", boost: 2 },
  { label: "Parameters", type: "type", detail: "TS utility", boost: 2 },
];

const cppKeywords: KeywordGroup[] = [
  { label: "alignas", type: "keyword" },
  { label: "alignof", type: "keyword" },
  { label: "and", type: "keyword" },
  { label: "and_eq", type: "keyword" },
  { label: "asm", type: "keyword" },
  { label: "auto", type: "keyword", boost: 1 },
  { label: "bitand", type: "keyword" },
  { label: "bitor", type: "keyword" },
  { label: "bool", type: "type", boost: 1 },
  { label: "break", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "char", type: "type", boost: 1 },
  { label: "class", type: "keyword", boost: 1 },
  { label: "compl", type: "keyword" },
  { label: "concept", type: "keyword", detail: "C++20" },
  { label: "const", type: "keyword", boost: 1 },
  { label: "consteval", type: "keyword", detail: "C++20" },
  { label: "constexpr", type: "keyword", boost: 1 },
  { label: "constinit", type: "keyword", detail: "C++20" },
  { label: "const_cast", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "co_await", type: "keyword", detail: "C++20" },
  { label: "co_return", type: "keyword", detail: "C++20" },
  { label: "co_yield", type: "keyword", detail: "C++20" },
  { label: "decltype", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "delete", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "double", type: "type" },
  { label: "dynamic_cast", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "enum", type: "keyword", boost: 1 },
  { label: "explicit", type: "keyword" },
  { label: "export", type: "keyword" },
  { label: "extern", type: "keyword" },
  { label: "false", type: "constant", boost: 1 },
  { label: "float", type: "type" },
  { label: "for", type: "keyword" },
  { label: "friend", type: "keyword" },
  { label: "goto", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "inline", type: "keyword" },
  { label: "int", type: "type", boost: 1 },
  { label: "long", type: "type" },
  { label: "mutable", type: "keyword" },
  { label: "namespace", type: "keyword", boost: 1 },
  { label: "new", type: "keyword" },
  { label: "noexcept", type: "keyword" },
  { label: "not", type: "keyword" },
  { label: "not_eq", type: "keyword" },
  { label: "nullptr", type: "constant", boost: 1 },
  { label: "operator", type: "keyword" },
  { label: "or", type: "keyword" },
  { label: "or_eq", type: "keyword" },
  { label: "private", type: "keyword", boost: 1 },
  { label: "protected", type: "keyword", boost: 1 },
  { label: "public", type: "keyword", boost: 1 },
  { label: "register", type: "keyword" },
  { label: "reinterpret_cast", type: "keyword" },
  { label: "requires", type: "keyword", detail: "C++20" },
  { label: "return", type: "keyword" },
  { label: "short", type: "type" },
  { label: "signed", type: "type" },
  { label: "sizeof", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "static_assert", type: "keyword", boost: 1 },
  { label: "static_cast", type: "keyword" },
  { label: "struct", type: "keyword", boost: 1 },
  { label: "switch", type: "keyword" },
  { label: "template", type: "keyword", boost: 1 },
  { label: "this", type: "keyword" },
  { label: "thread_local", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "true", type: "constant", boost: 1 },
  { label: "try", type: "keyword" },
  { label: "typedef", type: "keyword" },
  { label: "typeid", type: "keyword" },
  { label: "typename", type: "keyword" },
  { label: "union", type: "keyword" },
  { label: "using", type: "keyword", boost: 1 },
  { label: "virtual", type: "keyword" },
  { label: "void", type: "type", boost: 1 },
  { label: "volatile", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "std", type: "module", boost: 3 },
  { label: "cout", type: "variable", detail: "std", boost: 2 },
  { label: "endl", type: "constant", detail: "std", boost: 2 },
  { label: "cin", type: "variable", detail: "std", boost: 2 },
  { label: "vector", type: "class", detail: "std", boost: 2 },
  { label: "string", type: "class", detail: "std", boost: 2 },
  { label: "map", type: "class", detail: "std", boost: 2 },
  { label: "unordered_map", type: "class", detail: "std", boost: 2 },
  { label: "set", type: "class", detail: "std", boost: 2 },
  { label: "unordered_set", type: "class", detail: "std", boost: 2 },
  { label: "shared_ptr", type: "class", detail: "std", boost: 2 },
  { label: "unique_ptr", type: "class", detail: "std", boost: 2 },
  { label: "make_shared", type: "function", detail: "std", boost: 2 },
  { label: "make_unique", type: "function", detail: "std", boost: 2 },
  { label: "size_t", type: "type", boost: 2 },
  { label: "include", type: "keyword", detail: "preprocessor", boost: 1 },
  { label: "define", type: "keyword", detail: "preprocessor", boost: 1 },
  { label: "ifdef", type: "keyword", detail: "preprocessor" },
  { label: "ifndef", type: "keyword", detail: "preprocessor" },
  { label: "endif", type: "keyword", detail: "preprocessor" },
];

const sqlKeywords: KeywordGroup[] = [
  { label: "SELECT", type: "keyword", boost: 2 },
  { label: "FROM", type: "keyword", boost: 2 },
  { label: "WHERE", type: "keyword", boost: 2 },
  { label: "INSERT", type: "keyword", boost: 2 },
  { label: "INTO", type: "keyword" },
  { label: "VALUES", type: "keyword" },
  { label: "UPDATE", type: "keyword", boost: 2 },
  { label: "SET", type: "keyword" },
  { label: "DELETE", type: "keyword", boost: 2 },
  { label: "CREATE", type: "keyword", boost: 1 },
  { label: "TABLE", type: "keyword", boost: 1 },
  { label: "DROP", type: "keyword" },
  { label: "ALTER", type: "keyword" },
  { label: "INDEX", type: "keyword" },
  { label: "VIEW", type: "keyword" },
  { label: "JOIN", type: "keyword", boost: 1 },
  { label: "INNER", type: "keyword" },
  { label: "LEFT", type: "keyword" },
  { label: "RIGHT", type: "keyword" },
  { label: "OUTER", type: "keyword" },
  { label: "CROSS", type: "keyword" },
  { label: "ON", type: "keyword" },
  { label: "AS", type: "keyword" },
  { label: "AND", type: "keyword" },
  { label: "OR", type: "keyword" },
  { label: "NOT", type: "keyword" },
  { label: "IN", type: "keyword" },
  { label: "IS", type: "keyword" },
  { label: "NULL", type: "constant" },
  { label: "LIKE", type: "keyword" },
  { label: "BETWEEN", type: "keyword" },
  { label: "EXISTS", type: "keyword" },
  { label: "DISTINCT", type: "keyword" },
  { label: "GROUP", type: "keyword" },
  { label: "BY", type: "keyword" },
  { label: "HAVING", type: "keyword" },
  { label: "ORDER", type: "keyword" },
  { label: "ASC", type: "keyword" },
  { label: "DESC", type: "keyword" },
  { label: "LIMIT", type: "keyword" },
  { label: "OFFSET", type: "keyword" },
  { label: "UNION", type: "keyword" },
  { label: "ALL", type: "keyword" },
  { label: "CASE", type: "keyword" },
  { label: "WHEN", type: "keyword" },
  { label: "THEN", type: "keyword" },
  { label: "ELSE", type: "keyword" },
  { label: "END", type: "keyword" },
  { label: "BEGIN", type: "keyword" },
  { label: "COMMIT", type: "keyword" },
  { label: "ROLLBACK", type: "keyword" },
  { label: "TRANSACTION", type: "keyword" },
  { label: "PRIMARY", type: "keyword" },
  { label: "KEY", type: "keyword" },
  { label: "FOREIGN", type: "keyword" },
  { label: "REFERENCES", type: "keyword" },
  { label: "CONSTRAINT", type: "keyword" },
  { label: "DEFAULT", type: "keyword" },
  { label: "CHECK", type: "keyword" },
  { label: "UNIQUE", type: "keyword" },
  { label: "AUTO_INCREMENT", type: "keyword" },
  { label: "INTEGER", type: "type", boost: 1 },
  { label: "VARCHAR", type: "type", boost: 1 },
  { label: "TEXT", type: "type" },
  { label: "BOOLEAN", type: "type" },
  { label: "FLOAT", type: "type" },
  { label: "DOUBLE", type: "type" },
  { label: "DATE", type: "type" },
  { label: "TIMESTAMP", type: "type" },
  { label: "BLOB", type: "type" },
  { label: "COUNT", type: "function", boost: 2 },
  { label: "SUM", type: "function", boost: 2 },
  { label: "AVG", type: "function", boost: 2 },
  { label: "MIN", type: "function", boost: 2 },
  { label: "MAX", type: "function", boost: 2 },
  { label: "COALESCE", type: "function", boost: 2 },
  { label: "IFNULL", type: "function", boost: 2 },
  { label: "CAST", type: "function", boost: 2 },
  { label: "CONCAT", type: "function", boost: 2 },
  { label: "TRIM", type: "function", boost: 2 },
  { label: "UPPER", type: "function", boost: 2 },
  { label: "LOWER", type: "function", boost: 2 },
  { label: "LENGTH", type: "function", boost: 2 },
  { label: "SUBSTRING", type: "function", boost: 2 },
  { label: "REPLACE", type: "function", boost: 2 },
  { label: "ROUND", type: "function", boost: 2 },
  { label: "ABS", type: "function", boost: 2 },
  { label: "TRUE", type: "constant" },
  { label: "FALSE", type: "constant" },
];

const cssKeywords: KeywordGroup[] = [
  { label: "!important", type: "keyword" },
  { label: "align-content", type: "property" },
  { label: "align-items", type: "property", boost: 1 },
  { label: "align-self", type: "property" },
  { label: "animation", type: "property" },
  { label: "animation-delay", type: "property" },
  { label: "animation-direction", type: "property" },
  { label: "animation-duration", type: "property" },
  { label: "animation-fill-mode", type: "property" },
  { label: "animation-iteration-count", type: "property" },
  { label: "animation-name", type: "property" },
  { label: "animation-play-state", type: "property" },
  { label: "animation-timing-function", type: "property" },
  { label: "appearance", type: "property" },
  { label: "backdrop-filter", type: "property" },
  { label: "backface-visibility", type: "property" },
  { label: "background", type: "property", boost: 1 },
  { label: "background-color", type: "property", boost: 1 },
  { label: "background-image", type: "property" },
  { label: "background-position", type: "property" },
  { label: "background-repeat", type: "property" },
  { label: "background-size", type: "property" },
  { label: "border", type: "property", boost: 1 },
  { label: "border-radius", type: "property", boost: 1 },
  { label: "border-collapse", type: "property" },
  { label: "bottom", type: "property" },
  { label: "box-shadow", type: "property", boost: 1 },
  { label: "box-sizing", type: "property", boost: 1 },
  { label: "clear", type: "property" },
  { label: "clip-path", type: "property" },
  { label: "color", type: "property", boost: 1 },
  { label: "columns", type: "property" },
  { label: "content", type: "property" },
  { label: "cursor", type: "property" },
  { label: "display", type: "property", boost: 2 },
  { label: "filter", type: "property" },
  { label: "flex", type: "property", boost: 1 },
  { label: "flex-basis", type: "property" },
  { label: "flex-direction", type: "property", boost: 1 },
  { label: "flex-grow", type: "property" },
  { label: "flex-shrink", type: "property" },
  { label: "flex-wrap", type: "property" },
  { label: "float", type: "property" },
  { label: "font", type: "property" },
  { label: "font-family", type: "property", boost: 1 },
  { label: "font-size", type: "property", boost: 1 },
  { label: "font-style", type: "property" },
  { label: "font-weight", type: "property", boost: 1 },
  { label: "gap", type: "property", boost: 1 },
  { label: "grid", type: "property" },
  { label: "grid-area", type: "property" },
  { label: "grid-column", type: "property" },
  { label: "grid-row", type: "property" },
  { label: "grid-template-columns", type: "property" },
  { label: "grid-template-rows", type: "property" },
  { label: "height", type: "property", boost: 1 },
  { label: "justify-content", type: "property", boost: 1 },
  { label: "left", type: "property" },
  { label: "letter-spacing", type: "property" },
  { label: "line-height", type: "property", boost: 1 },
  { label: "margin", type: "property", boost: 1 },
  { label: "margin-top", type: "property" },
  { label: "margin-right", type: "property" },
  { label: "margin-bottom", type: "property" },
  { label: "margin-left", type: "property" },
  { label: "max-height", type: "property" },
  { label: "max-width", type: "property" },
  { label: "min-height", type: "property" },
  { label: "min-width", type: "property" },
  { label: "opacity", type: "property" },
  { label: "order", type: "property" },
  { label: "outline", type: "property" },
  { label: "overflow", type: "property" },
  { label: "padding", type: "property", boost: 1 },
  { label: "padding-top", type: "property" },
  { label: "padding-right", type: "property" },
  { label: "padding-bottom", type: "property" },
  { label: "padding-left", type: "property" },
  { label: "perspective", type: "property" },
  { label: "place-items", type: "property" },
  { label: "place-content", type: "property" },
  { label: "pointer-events", type: "property" },
  { label: "position", type: "property", boost: 2 },
  { label: "resize", type: "property" },
  { label: "right", type: "property" },
  { label: "rotate", type: "property" },
  { label: "scale", type: "property" },
  { label: "scroll-behavior", type: "property" },
  { label: "text-align", type: "property", boost: 1 },
  { label: "text-decoration", type: "property" },
  { label: "text-indent", type: "property" },
  { label: "text-overflow", type: "property" },
  { label: "text-shadow", type: "property" },
  { label: "text-transform", type: "property" },
  { label: "top", type: "property" },
  { label: "transform", type: "property", boost: 1 },
  { label: "transition", type: "property", boost: 1 },
  { label: "translate", type: "property" },
  { label: "user-select", type: "property" },
  { label: "vertical-align", type: "property" },
  { label: "visibility", type: "property" },
  { label: "white-space", type: "property" },
  { label: "width", type: "property", boost: 1 },
  { label: "word-break", type: "property" },
  { label: "word-wrap", type: "property" },
  { label: "z-index", type: "property", boost: 1 },
  { label: "block", type: "constant", detail: "display", boost: 2 },
  { label: "inline", type: "constant", detail: "display" },
  { label: "inline-block", type: "constant", detail: "display" },
  { label: "flex", type: "constant", detail: "display", boost: 2 },
  { label: "grid", type: "constant", detail: "display" },
  { label: "none", type: "constant", detail: "display" },
  { label: "absolute", type: "constant", detail: "position", boost: 2 },
  { label: "relative", type: "constant", detail: "position", boost: 2 },
  { label: "fixed", type: "constant", detail: "position" },
  { label: "sticky", type: "constant", detail: "position" },
  { label: "inherit", type: "constant" },
  { label: "initial", type: "constant" },
  { label: "unset", type: "constant" },
  { label: "center", type: "constant" },
  { label: "space-between", type: "constant" },
  { label: "space-around", type: "constant" },
  { label: "@media", type: "keyword", boost: 2 },
  { label: "@keyframes", type: "keyword", boost: 2 },
  { label: "@font-face", type: "keyword", boost: 1 },
  { label: "@import", type: "keyword", boost: 1 },
  { label: ":hover", type: "keyword", boost: 2 },
  { label: ":active", type: "keyword" },
  { label: ":focus", type: "keyword" },
  { label: ":first-child", type: "keyword" },
  { label: ":last-child", type: "keyword" },
  { label: ":nth-child", type: "keyword" },
  { label: "::before", type: "keyword" },
  { label: "::after", type: "keyword" },
  { label: "var()", type: "function", boost: 2 },
  { label: "calc()", type: "function", boost: 2 },
  { label: "min()", type: "function", boost: 1 },
  { label: "max()", type: "function", boost: 1 },
  { label: "clamp()", type: "function", boost: 1 },
  { label: "rgb()", type: "function" },
  { label: "rgba()", type: "function" },
  { label: "hsl()", type: "function" },
  { label: "linear-gradient()", type: "function", boost: 1 },
  { label: "radial-gradient()", type: "function" },
];

const htmlKeywords: KeywordGroup[] = [
  { label: "html", type: "type", boost: 2 },
  { label: "head", type: "type", boost: 2 },
  { label: "body", type: "type", boost: 2 },
  { label: "div", type: "type", boost: 3 },
  { label: "span", type: "type", boost: 3 },
  { label: "p", type: "type", boost: 3 },
  { label: "a", type: "type", boost: 3 },
  { label: "img", type: "type", boost: 2 },
  { label: "ul", type: "type", boost: 2 },
  { label: "ol", type: "type", boost: 2 },
  { label: "li", type: "type", boost: 2 },
  { label: "h1", type: "type", boost: 2 },
  { label: "h2", type: "type", boost: 2 },
  { label: "h3", type: "type", boost: 2 },
  { label: "h4", type: "type", boost: 2 },
  { label: "h5", type: "type", boost: 2 },
  { label: "h6", type: "type", boost: 2 },
  { label: "table", type: "type", boost: 2 },
  { label: "thead", type: "type", boost: 2 },
  { label: "tbody", type: "type", boost: 2 },
  { label: "tr", type: "type", boost: 2 },
  { label: "th", type: "type", boost: 2 },
  { label: "td", type: "type", boost: 2 },
  { label: "form", type: "type", boost: 2 },
  { label: "input", type: "type", boost: 2 },
  { label: "button", type: "type", boost: 2 },
  { label: "select", type: "type", boost: 2 },
  { label: "option", type: "type", boost: 2 },
  { label: "textarea", type: "type", boost: 2 },
  { label: "label", type: "type", boost: 2 },
  { label: "script", type: "type", boost: 2 },
  { label: "style", type: "type", boost: 2 },
  { label: "link", type: "type", boost: 2 },
  { label: "meta", type: "type", boost: 2 },
  { label: "title", type: "type", boost: 2 },
  { label: "header", type: "type", boost: 2 },
  { label: "footer", type: "type", boost: 2 },
  { label: "nav", type: "type", boost: 2 },
  { label: "main", type: "type", boost: 2 },
  { label: "section", type: "type", boost: 2 },
  { label: "article", type: "type", boost: 2 },
  { label: "aside", type: "type", boost: 2 },
  { label: "iframe", type: "type", boost: 2 },
  { label: "canvas", type: "type", boost: 2 },
  { label: "video", type: "type", boost: 2 },
  { label: "audio", type: "type", boost: 2 },
  { label: "source", type: "type", boost: 2 },
  { label: "br", type: "type", boost: 2 },
  { label: "hr", type: "type", boost: 2 },
  { label: "pre", type: "type", boost: 2 },
  { label: "code", type: "type", boost: 2 },
  { label: "strong", type: "type", boost: 2 },
  { label: "em", type: "type", boost: 2 },
  { label: "class", type: "property", boost: 3 },
  { label: "id", type: "property", boost: 3 },
  { label: "href", type: "property", boost: 2 },
  { label: "src", type: "property", boost: 2 },
  { label: "alt", type: "property", boost: 2 },
  { label: "title", type: "property", boost: 2 },
  { label: "style", type: "property", boost: 2 },
  { label: "type", type: "property", boost: 2 },
  { label: "value", type: "property", boost: 2 },
  { label: "name", type: "property", boost: 2 },
  { label: "placeholder", type: "property", boost: 2 },
  { label: "disabled", type: "property", boost: 2 },
  { label: "readonly", type: "property", boost: 2 },
  { label: "required", type: "property", boost: 2 },
  { label: "hidden", type: "property", boost: 2 },
  { label: "onclick", type: "property", boost: 1 },
  { label: "onchange", type: "property", boost: 1 },
  { label: "onsubmit", type: "property", boost: 1 },
  { label: "onload", type: "property", boost: 1 },
  { label: "onerror", type: "property", boost: 1 },
];

const xmlKeywords: KeywordGroup[] = [
  { label: '<?xml version="1.0"?>', type: "keyword", boost: 2 },
  { label: '<?xml version="1.0" encoding="UTF-8"?>', type: "keyword", boost: 2 },
  { label: "xmlns", type: "property", boost: 2 },
  { label: "xsi:schemaLocation", type: "property", boost: 1 },
  { label: "encoding", type: "property", boost: 1 },
  { label: "version", type: "property", boost: 1 },
];

const yamlKeywords: KeywordGroup[] = [
  { label: "true", type: "constant", boost: 1 },
  { label: "false", type: "constant", boost: 1 },
  { label: "null", type: "constant", boost: 1 },
  { label: "yes", type: "constant" },
  { label: "no", type: "constant" },
  { label: "on", type: "constant" },
  { label: "off", type: "constant" },
];

const jsonKeywords: KeywordGroup[] = [
  { label: "true", type: "constant", boost: 2 },
  { label: "false", type: "constant", boost: 2 },
  { label: "null", type: "constant", boost: 2 },
];

const markdownKeywords: KeywordGroup[] = [
  { label: "# ", type: "keyword", detail: "heading 1", boost: 2 },
  { label: "## ", type: "keyword", detail: "heading 2", boost: 2 },
  { label: "### ", type: "keyword", detail: "heading 3", boost: 2 },
  { label: "#### ", type: "keyword", detail: "heading 4", boost: 1 },
  { label: "##### ", type: "keyword", detail: "heading 5", boost: 1 },
  { label: "###### ", type: "keyword", detail: "heading 6", boost: 1 },
  { label: "- ", type: "keyword", detail: "unordered list", boost: 2 },
  { label: "* ", type: "keyword", detail: "unordered list", boost: 2 },
  { label: "1. ", type: "keyword", detail: "ordered list", boost: 2 },
  { label: "> ", type: "keyword", detail: "blockquote", boost: 2 },
  { label: "---", type: "keyword", detail: "horizontal rule", boost: 2 },
  { label: "```", type: "keyword", detail: "code block", boost: 2 },
  { label: "**", type: "keyword", detail: "bold" },
  { label: "__", type: "keyword", detail: "bold" },
  { label: "*", type: "keyword", detail: "italic" },
  { label: "_", type: "keyword", detail: "italic" },
  { label: "[", type: "keyword", detail: "link start" },
  { label: "![", type: "keyword", detail: "image start" },
  { label: "| ", type: "keyword", detail: "table cell" },
];

type LanguageCompletions = Record<string, KeywordGroup[]>;

const allCompletions: LanguageCompletions = {
  python: pythonKeywords,
  java: javaKeywords,
  rust: rustKeywords,
  go: goKeywords,
  javascript: jsTsKeywords,
  typescript: [...jsTsKeywords, ...tsExtraKeywords],
  c: cppKeywords,
  cpp: cppKeywords,
  h: cppKeywords,
  hpp: cppKeywords,
  sql: sqlKeywords,
  css: cssKeywords,
  scss: cssKeywords,
  less: cssKeywords,
  html: htmlKeywords,
  xml: xmlKeywords,
  yaml: yamlKeywords,
  toml: yamlKeywords,
  json: jsonKeywords,
  markdown: markdownKeywords,
};

function completionSourceFor(language: string) {
  const keywords = allCompletions[language];
  if (!keywords) return null;
  const options = makeCompletions(keywords);
  return function completions(context: CompletionContext): CompletionResult | null {
    const word = context.matchBefore(/[\w#@:!`*\-[\]]+$/);
    if (!word) return null;
    if (word.from === word.to && !context.explicit) return null;
    return {
      from: word.from,
      options,
      validFor: /^[\w#@:!`*\-[\]]*$/,
    };
  };
}

export { completionSourceFor };
